### ISSUE TITLE
Group wcadmin not created but required

### ISSUE THREAD

**Issue by m-o-n-k** [telusdigital/ansible-taiga#2]
Play cancels with error message:
```
TASK [telusdigital.taiga : Directory Exists | taiga] ***************************
fatal: [qa-taiga]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chgrp failed: failed to look up group wcadmin", "owner": "root", "path": "/srv/taiga.io", "size": 4096, "state": "directory", "uid": 0}
```

After manually creating the group the error is gone.

My config:
```
vars:
  environment_tier: production
  taiga_install_root: /srv/taiga.io
  taiga_database_host: localhost
  taiga_database_password: - removed -
  taiga_database_username: taiga
  taiga_email_host: - removed -
  taiga_from_email_address: - removed -
  taiga_hostname: - removed -
  taiga_public_register_enabled: False
  taiga_url_scheme: https
```
